### ISSUE TITLE
CachingTest.getCacheManager_nonNullProperties() is faulty

### ISSUE THREAD

**Issue by ocafebabe** [jsr107/jsr107tck#102]
I don't understand how this test can be valid when a specific implementation doesn't use an empty properties object as its default properties! 

The first call to `provider.getCacheManager()` will create a new CacheManager using the **default properties** of the provider (and in my case I actually have default values) and the second call to :

``` java
provider.getCacheManager(provider.getDefaultURI(), provider.getDefaultClassLoader(), new Properties())
```

will return the same CacheManager instance (since, as the specifications clearly says, the properties do not form part of the identity of the CacheManager). At this point it's all good!

But my problem arises on the second assertion:

``` java
assertEquals(properties, manager.getProperties());
```

Here the expected value is the empty properties object that was created at the beginning of the test and the actual value is the properties object returned from the CacheManager which in my case cannot be equal simply because (as I said earlier) my default properties is not an empty properties object!

Does it make sense?

**Comment by cruftex** [comment]
Good finding. Thanks for reporting this. Everybody seems to use empty properties as default,
 so it wasn't noticed yet.

I can see three issues:
- The cache manager is created with default properties in the first place
- The cache manager might be existing since it is created by another test
- Testing with empty properties is meaning less. The test cannot assert whether its own properties get picked up.

Suggest the following test for it:

````
  @Test
  public void getCacheManager_nonNullProperties() {
    // make sure existing cache managers are closed and the non empty properties get picked up
    try {
      Caching.getCachingProvider().close();
    } catch (CacheException ignore) {
      // ignore exception which may happen if the provider is not active
    }
    CachingProvider provider = Caching.getCachingProvider();
    Properties properties = new Properties();
    properties.put("dummy.com", "goofy");
    provider.getCacheManager(provider.getDefaultURI(), provider.getDefaultClassLoader(), properties);
    CacheManager manager = provider.getCacheManager();
    assertEquals(properties, manager.getProperties());
  }
````

This fails for the RI. There is a bug in the CacheManager constructor:

````
    this.properties = properties == null ? new Properties() : new Properties(properties);
````

Unfortunately, `Properties` has no copy constructor. 

Before we go forward and change the TCK, I'd like to asses the existing implementations about this behavior.

**Comment by ocafebabe** [comment]
Hey @cruftex, just to let you know that I tested my [implementation](https://github.com/ocafebabe/guava-jcache) with your new test version and it works perfectly! Thanks!

**Comment by cruftex** [comment]
Thanks for the feedback!

Just realized that this test is dangerous. In case custom properties are provided, those need to get picked up, but it isn't really useful that these properties must become the only ones.

Furthermore the spec says: 

> the {@link Properties} for the {@link 
> to create the {@link CacheManager} (null means no
> implementation specific Properties are required)

Consequently, when properties are provided, these are interpreted in an implementation specific way. How can the TCK assert a specific behavior then?

**Comment by cruftex** [comment]
As per last comment, created PR to remove this test.

Opened a Spec issue for it: https://github.com/jsr107/jsr107spec/issues/368
Tests can be added again, when behavior is specified.

**Comment by gregrluck** [comment]
Created #55 in the RI. Properties were simply not being copied from the constructor parameter. Fixed that, now Jens modified test passes.

**Comment by jfialli** [comment]
Given the lack of a copy constructor for java.util.Properties, I strongly recommend to remove following assertion from TCK test.
    assertEquals(properties, manager.getProperties());

It is quite difficult to preserve defaults and Properties set explicitly with setProperty().
Safest to just test that the property value pair in question is preserved.

     assertEquals("goofy", manager.getProperties().getProperty("dummy.com"));

If there is a desire to preserve default properties, one must rely on Properties.stringPropertyName().
https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html#stringPropertyNames()

**Comment by cruftex** [comment]
> I strongly recommend to remove following assertion from TCK test. assertEquals(properties, manager.getProperties());

+1

> Safest to just test that the property value pair in question is preserved.

````
 assertEquals("goofy", manager.getProperties().getProperty("dummy.com"));
````

The Spec doesn't say that properties have to be preserved and how properties are interpreted is implementation specific. A legal implementation may refuse operation if there are any properties.

If there is the assumption that properties are preserved and an implementation ignores properties which are not in its namespace, then we need to put that in the Spec first.

In https://github.com/jsr107/jsr107spec/issues/368 Greg opted for a. That means everything non null is implementation specific, so we cannot test anything here.

Suggest removing the test, the PR is pending any ways.

**Comment by cruftex** [comment]
@jfialli, I think it is better to reopen https://github.com/jsr107/jsr107spec/issues/368 and put more detail in the Spec how this should behave.

**Comment by vbekiaris** [comment]
I would propose to [fix the assertion](https://github.com/jsr107/jsr107tck/issues/126) as discussed [above](https://github.com/jsr107/jsr107tck/issues/102#issuecomment-267596515) instead of removing the test altogether: we should assert that `CacheManager.getProperties()` returns (at least) the properties that were used to create the `CacheManager`, according to its javadoc:

```
  /**
   * Get the {@link Properties} that were used to create this
   * {@link CacheManager}.
   * <p>
   * Implementations are not required to re-configure the
   * {@link CacheManager} should modifications to the returned
   * {@link Properties} be made.
   *
   * @return the Properties used to create the {@link CacheManager}
   */
  Properties getProperties();
```

**Comment by cruftex** [comment]
> we should assert that CacheManager.getProperties() returns (at least) the properties that were used to create the CacheManager

The specification isn't sufficient to add a test like this. I tried to clarify that in https://github.com/jsr107/jsr107spec/issues/368

According to the JavaDoc, as you point out, the Spec says that the Properties are going through transparently. However, since the meaning of the properties is implementation specific, you cannot set any property.For example, according to the Spec it would be legal for an implementation to raise an exception if any property is set. Okay, that's far fetched, but there is a gap in the Spec.

The Spec needs to define proper property scopes, so you can test properties that don't have an effect on the cache implementation.

I would be in favor of it. Since there are not so many TCK tests for properties, and there is quite some diversity in the implementations with different semantics.

**Comment by vbekiaris** [comment]
@cruftex thanks for the explanation, makes sense.

> I would be in favor of it.

My understanding is for 1.1.0 we should merge #126 and close #108 , right?

**Comment by cruftex** [comment]
I mean when we add tests, we should also clarify/extend the Spec in this topic. What we have as PRs for the TCK isn't sufficient. The Spec should:

- State that property keys have scope and cache implementations may only react to properties within their defined scope
- Define the semantics when the properties get mutated / meaning mutating the properties returned by `CacheManager.getProperties()` will be visible (or not)

**Comment by cruftex** [comment]
Proposed solution(s):

**a) Properties are completely implementations specific.**

=> Remove any TCK tests with non empty properties.

**b) Properties are passed through transparently**

Change in `CachingProvider` this:

````
Properties are caching implementation specific. The behavior of mutating
properties obtained from {@link CacheManager#getProperties()} is undefined.
````

to:

````
Properties name follow the same scheme as package names.
The prefixes {@code java} and {@code javax} are reserved.
Properties are passed through and and can be retrieved via {@link CacheManager#getProperties()}.
Properties within the package scope of a caching implementation may be used for
additional configuration.
````

JavaDoc of `CacheManager.getProperties()` should read:

````
Get the {@link Properties} that were used to create this {@link CacheManager} with {@link CachingProvider#getCacheManager...}. The behavior of mutating the
obtained properties is undefined.
````

Add TCK tests to check that properties pass through.
