### ISSUE TITLE
The TCK repository should be private

### ISSUE THREAD

**Issue by brianoliver** [jsr107/jsr107tck#117]
The TCK source, binary and user guide should only be available via download from the JCP once licensees have agreed to the SATCK license.   It should not be made available without agreeing to this license, for example, publicly on github.

**Comment by gregrluck** [comment]
I have looked some examples.

https://jcp.org/aboutJava/communityprocess/mrel/jsr356/index.html
TCK: Existing licensees can use the Java Partner Engineering access page for the Technology Compatibility Kit.

Money API
https://jcp.org/aboutJava/communityprocess/final/jsr354/index.html
Technology Compatibility Kit on maven central
TCK source code on Github

JCP 2.9 is silent on this point.

The [Spec Lead Guide](https://jcp.org/en/resources/speclead_life_p5) states:
"David doesnt recommend having the TCK and RI developed in isolation from each other. In fact, he thinks it makes sense to have the RI developers write test cases for the TCK since they understand the specification thoroughly. He says open sourcing both the TCK and the RI in a liberal open source license would help enable such useful transparency. "

**Comment by gregrluck** [comment]
Spoke to Brian about this today. He thinks that with the license header change in the source code files, that should be sufficient. So closing this issue.
