### ISSUE TITLE
incorrect cache-api version in pom.xml files

### ISSUE THREAD

**Issue by rfqu** [jsr107/jsr107tck#127]
Both jsr107/pom.xml and RI/pom.xml contain dependency:

`<groupId>javax.cache</groupId>
        <artifactId>cache-api</artifactId>
<version>1.1.0-SNAPSHOT</version>`

However, such a version could not be found, and build process fails.

workaround: set 
`<version>1.0.0</version>`

**Comment by cruftex** [comment]
That is correct since the latest TCK code is to be build and run with the latest RI and Spec (cache-api) code. If you want to build&run the latest TCK code, do `mvn install` on the Spec and RI project first to have a snapshot version in your local repository. Hope that helps. 

If you think something is wrong please provide more background information on what you actually want to accomplish. Closing the issue for now, since I don't see a needed action here.
