### ISSUE TITLE
TCK uses "implementation-version" for cache-annotations-ri-cdi and similar artifacts

### ISSUE THREAD

**Issue by eolivelli** [jsr107/jsr107tck#134]
I am running the candidate TCK of JCache 1.1, it seems that it is using implementation-version for cache-annotations-ri-cdi and similar artifacts

**Comment by eolivelli** [comment]
Created pull request #135

**Comment by vbekiaris** [comment]
@eolivelli thanks for testing with the candidate TCK. The behavior is the same with latest released TCK 1.0.1 so this is not a new regression: when running the `jsr107tck` build with any implementation artifact whose version is not `1.0.0`, the annotation test harness modules build fails due to inability to locate artifact `org.jsr107.ri:cache-annotations-ri-*:${implementation-version}`. That said, I would be in favor of merging your solution. Let's see what others think /cc @cruftex ?

**Comment by cruftex** [comment]
If you fix the RI version, you can actually remove the modules in question. Since it is a dependency on the RI you need to introduce another variable for the latest RI version.

I am really not sure what the intention of those module is. My "gut feeling" is that it tests the demo annotations in the RI and actually should be moved over there. Then the build dependency on the RI is gone altogether, which is, IMHO, the right thing.

**Comment by eolivelli** [comment]
The only meaning of those tests maybe to test the candidate implementation to be able to work together with other components. It can be quite useless.
Anyway actually it is not possible to run the full TCK without tweaking those poms.
I think every user has the same problem.
Or we have to give a specific guide to run the only part of the TCK which makes sense.

I will be +1 on moving all those tests to the RI as well

**Comment by cruftex** [comment]
> Anyway actually it is not possible to run the full TCK without tweaking those poms.
> I think every user has the same problem.

I think so too:
https://github.com/jsr107/jsr107tck/issues/110

The best is to check and follow the recent TCK guide here:
https://docs.google.com/document/d/1m8d1Z44IFGAd20bXEvT2G--vWXbxaJctk16M2rmbM24/edit#heading=h.ob5ac0uks4kx
(The link is referenced in: https://github.com/jsr107/jsr107tck/blob/master/README.md)

If this does not work, then file an issue with the actual outcome.

Maybe it works if you build and install the RI first, but this is not mentioned in the guide.

**Comment by cruftex** [comment]
Although the best solution would be to correct the structuring, I am not so happy to move bunches of code between git repositories within maintenance. It is confusing and changes are hard to track.

**Comment by gregrluck** [comment]
I see the problem. It works in my build because the RI is used but when testing any other implementation it picks up that implementation's version e.g. Hazelcast 3.9.2.

Rather than hardcoding I have changed it to ${project.parent.version} which should work for everyone.
