### ISSUE TITLE
CacheListenerTest assertions and exceptions from listeners may not fail tests

### ISSUE THREAD

**Issue by vbekiaris** [jsr107/jsr107tck#141]
Affects TCK versions 1.0.x and 1.1.0

Under "Invocation of listeners" the specification reads (page 74 version 1.0, page 76 version 1.1.0):
>  (Cache Listeners) if synchronous, are fired, for a given key, in the order in that events occur, blocking the calling thread until the listener returns
...
A listener is not required to be in­-process with the originating event.

Javadoc of `CacheEntryListenerConfiguration#isSynchronous`:
```
  /**
   * Determines if the thread that caused an event to be created should be
   * blocked (not return from the operation causing the event) until the
   * {@link CacheEntryListener} has been notified.
   *
   * @return <code>true</code> if the thread that created the event should block
   */
```

The spec does not impose execution of listeners in-process or on the same thread as the cache operation from which events originate, however the tests in `CacheListenerTest` fail to catch assertion errors or other exceptions thrown from test listeners `MyCacheEntryListener`, `MyBrokenCacheEntryListener` when the implementation is executing listeners on another thread. The tests work as intended with the RI, as it executes listeners in the same thread that executes the cache operation, but may not detect failures from implementations that publish events on other threads.

For example `testBrokenCacheEntryListener` tests expected exceptions like this:
```
    try {
      cache.put(1l, "Sooty");
    } catch (CacheEntryListenerException e) {
      //expected
    }
```

When running with the RI, the exception is indeed thrown as expected and ignored. However running TCK 1.0.1 with Hazelcast 3.5.2 (as an example of an implementation that publishes events on other threads) no exception is thrown; this goes undetected because there is a missing `fail` statement. The test should read instead:

```
    try {
      cache.put(1l, "Sooty");
      fail("A CacheEntryListenerException should have been thrown");
    } catch (CacheEntryListenerException e) {
      //expected
    }
```

When the test is fixed to include the `fail` statement, it fails because no exception is thrown on the test thread. Since no assumptions can be made about the execution of listeners, the tests in `CacheListenerTest` should use other means to communicate failures from the test listener's implementation to the test.

**Comment by cruftex** [comment]
> When the test is fixed to include the fail statement, it fails because no exception is thrown on the test thread.

Fixing the test would the obvious thing, but maybe other vendors have the same issue as Hazelcast. Lots of work could be caused without any "user" raising an actual problem.

> Since no assumptions can be made about the execution of listeners, the tests in `CacheListenerTest` should use other means to communicate failures from the test listener's implementation to the test.

No. There is no assumption in what context the `CacheWriter` is called, as well. However, for the cache writer, exceptions must be propagated, because the operation is incomplete in case of an exception. AFAIK we test this  properly.

For a synchronous listener call exceptions can be propagated as well. Exceptions are serializable. 

Is there any test or usage of the `CacheEntryListenerException` at all?

> the tests in CacheListenerTest should use other means to communicate failures from the test listener's implementation to the test.

The test can only test things that is in the specification. There is no "other means" in the specification. The existence of the exception means that it meant to be thrown, and the test tries to assure that, but is incorrect.

Personally I am always in strong favor in propagating exceptions, because "other means" usually means  logging and problems will stay unnoticed. I would encourage every vendor to do so, but would rather not "enforce" it at this late time.

**Comment by cruftex** [comment]
Maybe there is a compromise: Fix the test, but comment that implementations may skip it. This way vendors are more pointed in the right direction.

**Comment by vbekiaris** [comment]
> For a synchronous listener call exceptions can be propagated as well.

That's a very good point actually, thanks for highlighting it. Even though it is a rational expectation, I am not sure it is mandated by the spec, neither is it actually enforced by the TCK (due to the missing `fail()` statements in `CacheListenerTest`).

> Lots of work could be caused without any "user" raising an actual problem.

Given that this test has been around since 1.0 with the same structure and no-one else raised an issue, I think we can just leave this issue open for some days. If there is no interest from anyone else in doing more work on this, let's just close it as a won't fix; I don't see this as critical at this point (ie it's not failing the TCK for valid implementations).

**Comment by vbekiaris** [comment]
Closing this issue as discussed above.
