### ISSUE TITLE
Tests should fail with timeouts

### ISSUE THREAD

**Issue by ben-manes** [jsr107/jsr107tck#74]
The tests assume the happy path execution of a fully compliant implementation in a perfect environment. It therefore does not include any type of timeouts or circuit breakers. This is a bad assumption.

Examples include [CacheExpiryTest](https://github.com/jsr107/jsr107tck/blob/master/cache-tests/src/test/java/org/jsr107/tck/expiry/CacheExpiryTest.java#L767) which blocks on a future forever. Another is that the client may fail to connect to the server on a macbook unless the system property `java.net.preferIPv4Stack` is set.

The TCK should assume that it is being used to drive the development of an implementation, rather than verifying one that magically materialized flawlessly in full.

**Comment by cruftex** [comment]
Ben,

I ran in the same problem and had the same thoughts. But putting timeouts in the tests is not an option for various reasons:

1. The tests should be clear about what gets tested. Putting a timeout on a test, e.g.7 seconds, implies a semantically constraint that is not specified. But the TCK is the specification.

2. If 300 tests get stuck, a timeout of 7 seconds does not help the developer to be more productive.

3. It does drive development, the things that get stuck needs to be examined first.

4. Putting a timeout on the tests means that the execution cannot be stopped and continued. Bad for developers, because the debugger cannot be used.

For CI tests a global timeout is sufficient, which can be added as a command line parameter when running the tests.

Suggest to close.

**Comment by gregrluck** [comment]
The purpose of the TCK is to prove that an implementation implements the spec. Its purpose is not as you say  "used to drive the development of an implementation".
