### ISSUE TITLE
Use a unique port for each test

### ISSUE THREAD

**Issue by ben-manes** [jsr107/jsr107tck#78]
`CacheLoaderTest` uses a hardcoded port for the `CacheLoaderServer`. If tests are run too quickly then a race condition may occur where the server receives messages fired from previous test results. This causes intermittent test failures where logically they could never occur otherwise, such as in `shouldNotLoadUsingReplace`.

When setting the test to use a unique port number, via a static `AtomicInteger`, the failures are not reproducible. As a workaround, the test is run in isolation to minimize the chance of race conditions while retaining full TCK coverage.

The proposed change is something like,

``` java
private static final AtomicInteger port = new AtomicInteger(10000);

@Before
public void onBeforeEachTest() throws IOException {
  cacheLoaderServer = new CacheLoaderServer<String, String>(port.getAndIncrement());
```

**Comment by cruftex** [comment]
Just a quick look, after the test, the cache is shut down:

```` java
    public void onAfterEachTest() {
      //destroy the cache
      String cacheName = cache.getName();
      cacheManager.destroyCache(cacheName);

      //close the server
      cacheLoaderServer.close();
      cacheLoaderServer = null;

      cache = null;
    }
````

So why is the cache initiating new connections after being shut down?

This can happen when:
- The cache does not wait for calls the the loader to finish
- The cache does something asynchronously (Cache.load() Cache.loadAll())
- The application does not wait for calls to the loader to finish

The only test case this applies to is this one:

    CacheLoaderTest.testLoadAllWithExecptionAndNoCompletionListener()

Maybe you can put that on the exclude list until this is resolved?

Assigning a static port is bad.

There is already code for resolving conflicts in Server.java:

```` java
    private ServerSocket createServerSocket() throws IOException {

        final int ephemeralPort = 0;
        ServerSocket result = null;
        try {
            result = new ServerSocket(port);
        } catch (IOException e) {

            // requested port may still be in use due to linger on close on some OSs,
            // use ephemeral port for server socket
            result = new ServerSocket(ephemeralPort);
            LOG.warning("createServerSocket: unable to use requested port " + port +
                    "; using ephemeral port " + result.getLocalPort());
            this.port = result.getLocalPort();
        }
        LOG.log(Level.INFO, "Starting " + this.getClass().getCanonicalName() +
                " server at address:" + getServerInetAddress() + " port:" + port);
        return result;
    }
````

The best solution would be, just to remove the static ports from the server constructors and let the server do it by itself.

**Comment by ben-manes** [comment]
Yes, I thought it was clear that this is due to asynchronous actions due to `CacheLoaderServer` being used in multiple test classes.

The TCK authors intentionally applied a bad practice of static ports, perhaps to simplify distributed tests by having a known port range. Regardless, I'd rather not distract from this issue being fixed to best practices, as that would reduce the likelihood of any fix being applied. I showed a simple hack to demonstrate the issue, assuming the authors were experienced enough to implement it however they see best.

As mentioned, I have a workaround by running the `CacheLoaderTest` class independently to avoid races. This adds slight complexity to the build and retains full TCK coverage. That is preferable to excluding the test(s) entirely.

**Comment by cruftex** [comment]
I needed to outline the causality of this race (primarily for myself.... and maybe also for others to follow). 

The interesting side track of this:

A solution for the problem can be, that caches always wait for asynchronous operation to finish when destroyed. Destroy is defined as clear() and close(). What are useful semantics of clear() when asynchronous operations are going on? IMHO we should not delay lifecycle operation, but things get really messy here....

> The TCK authors intentionally applied a bad practice of static ports, perhaps to simplify distributed tests by having a known port range.

The 10000 port number is in the CacheWriterTest, too and probably elsewhere. This violates DRY and it is because nobody had the time to go over it and make everything as nice and clean as possible.

Did you run the CacheWriterTest often enough to be sure that this has no race?

You discovered a problem. Let's move forward, learn and fix it and not just cure one single symptom.

If needed, I can put together a pull request for this, or two.

**Comment by cruftex** [comment]
If we do improve, I'd like it to meet these requirements:

- more then one TCK test suites should be able to run on the same machine in different JVMs without interfering
- speed improvement, since creating sockets and network communications slows down the tests

**Comment by cruftex** [comment]
Opened #93, since meanwhile I am not sure why this is needed.

**Comment by cruftex** [comment]
I think the race condition is gone, since the TCK properly calls close on the customizations, which was done in:
https://github.com/jsr107/jsr107tck/issues/100

**Comment by cruftex** [comment]
The TCP communications stuff is actually not really needed when all runs in a single JVM.
I made some experimental changes to the TCK that don't use the TCP communication in this case, which reduces the test execution down to about 1s. See:

https://github.com/cache2k/cache2k/blob/master/cache2k-jcache-tests/src/main/java/org/jsr107/tck/support/Server.java

and

https://github.com/cache2k/cache2k/commit/b59c30f38001bafb33a8ec74330efac157a2751a

**Comment by gregrluck** [comment]
As I recall this is needed for the Coherence implementation which is tested as a cluster. So can we please leave the plumbing there.

**Comment by cruftex** [comment]
Since we believe that the original race is gone with #100, we close this one. If there are any remaining problems, please reopen.

**Comment by brianoliver** [comment]
A quick follow up here.  In principle this has nothing to do with Coherence, but more due to the fact that the CacheWriter/CacheLoader could be executed anywhere.  From what I recall there's no requirement or constraints placed on their use/execution in the specification, so no assumptions should ever be made anywhere in the TCK as to where something would execute, unless explicitly stated.  Hope this helps.

eg: Assuming these things work locally or should is a violation of the spec, which makes no such requirements, because we worked very hard to make it topology agnostic.
