### ISSUE TITLE
EntryProcessor and Iterators should update Cache Access / Mutation Statistics. 

### ISSUE THREAD

**Issue by brianoliver** [jsr107/jsr107tck#81]
This applies to the following TCK methods in  org.jsr107.tck.management.CacheMBStatisticsBeanTest:

* testCacheStatisticsInvokeEntryProcessorRemove
* testCacheStatisticsInvokeEntryProcessorUpdate 
* testCacheStatisticsInvokeEntryProcessorGet
* testCacheStatisticsInvokeEntryProcessorNoOp
* testIterateAndRemove

These methods check whether a miss, hit or get  is counted, but the data is not read via Entry.getValue().

With this requirement the statistic counters will not show relevant information as soon as Iterator or the EntryProcessor is used.

To put it more formal, the statement

    boolean present = cache.containsKey(key);

and the statement

    boolean present = invoke(key, new EntryProcessor<K, V, Boolean>() {
      @Override
      public Boolean process(MutableEntry<K, V> entry, Object... arguments) {
        return entry.exists();
      }
    });

should have identical semantics. It should be possible to augment any other cache operation via invoke() / invokeAll()

For the Iterator it makes sense that the value is always accessed, since a user of the Iterator interface will imply that the iterated entries always satisfy: Entry.getValue() != null.

For the EntryProcessor this is not the case, Entry.getValue() aka MutableEntry.getValue() may return null.

IMHO, the best possible enhancement would be:

- TCK checks that hit, get and miss counter is not updated when EntryProcessor user is not requesting the value
- TCK checks on iterator statistics stay the same
- Addition to interface contract Entry.getValue(): always returns a non-null value
- Addition to interface contract MutableEntry.getValue(): Overridden contract, may return null value

**Comment by cruftex** [comment]
> It should be possible to augment any other cache operation via invoke() / invokeAll()

The spec defines that the operations `putIfAbsent` and `replace` do update the hit and miss statistics although the entry value was never accessed. 

The spec is irregular here, since it defines no hit and miss change for `containsKey`. Because of this, it is never achievable that the changes in the statistics are identical if normal cache operation semantics are implemented with the entry processor.

Changing the implementations for a higher goal that we cannot achieve with the current spec is not very efficient. So, I think we can close this.
