### ISSUE TITLE
Version should be 1.1-SNAPSHOT

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107tck#82]
Just saw that the version was updated to 1.0.1-SNAPSHOT, however 1.0.1 is released already.
For the upcoming release it should be 1.1-SNAPSHOT. That is a popular pitfall. See:

https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN401

**Comment by keilw** [comment]
+1 although it might be 1.0.2-SNAPSHOT, depending on a strategy for necessary updates to fit into Java EE 8?;-O Skiping to 2.0 does not sound too reasonable, but a brand new JSR could use 1.1 and above. Unless the TCK won't be touched with MR1 or already got there with 1.0.1-release. If changes are necessary for a not yet filed MR1, then the TCK would have to go with 1.0.2, since 1.0.1 went out as a "Patch" or Service Release already;-)

**Comment by cruftex** [comment]
Version was changed to 1.1.0-SNAPSHOT.
