### ISSUE TITLE
TCK Exception Assertions wrong for CacheManager.getCache(String, Class<K>, Class<V>)

### ISSUE THREAD

**Issue by jfialli** [jsr107/jsr107tck#86]
### TCK Challenge:

The TCK asserts a java.lang.ClassCastException in tests listed below but pg 23 of the spec and the javadoc for CacheManager.getCache(String, Class<K>, Class<V>) state that IllegalArgumentException is thrown if the specified key and/or value types are incompatible with the configured cache.

### From TCK report output:
Tests in error: 
getIncorrectCacheValueType(org.jsr107.tck.CacheManagerTest): Unexpected exception, expected\<java.lang.ClassCastException\> but was\<java.lang.IllegalArgumentException\>
  getIncorrectCacheType(org.jsr107.tck.CacheManagerTest): Unexpected exception, expected\<java.lang.ClassCastException\> but was\<java.lang.IllegalArgumentException\>

### Proposed Resolution:

Update the CacheManagerTest.java  as follows:

>  << @Test(expected = ClassCastException.class)
> \>\> @Test(expected = IllegalArgumentException.class)
>        public void getIncorrectCacheType() {

>    
>  <<  @Test(expected = ClassCastException.class)
>  \>\>  @Test(expected = IllegalArgumentException.class)
>         public void getIncorrectCacheValueType() {

**Comment by cruftex** [comment]
ClassCastException is the better one, since more specific. Suggest changing the Spec instead.

Changing this in the TCK would mean every implementation needs to change to something less desirable. Uncle bob says "Do no harm", so let's make one change for the better instead of many for the worse.

Is this also okay for you?

Remark:
I think that your TCK challenge is totally valid. The TCK should verify what the Spec says.

The practical situation is that the TCK checks a lot of things that is not in the Spec at all (e.g. very precise statistics checks). So the TCK is more complete and more precise then the Spec and may be sometimes even more correct.

**Comment by cruftex** [comment]
Bundling with
https://github.com/jsr107/jsr107spec/issues/361
since same Method.

I think changing the Spec JavaDoc to require `ClassCastException` is the pragmatic way. This doesn't require anybody to change their implementation.
